development:
  adapter: mysql2
  database: vintenews_dev
  pool: 5
  username: root
  password:
  encoding: utf8
  reconnect: true

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
