development:
  adapter: mysql
  host: localhost
  username: root
  password: 
  database: vintenews_dev

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
